services:
  app:
    image: node:lts-slim
    environment:
      - NGINX_BACKEND_ADDRESS=http://backend:3000
    depends_on: 
      - backend
      - db
    command: npx vite --host
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - 5173:5173

  backend:
    image: node:lts-slim
    environment:
      - DATABASE_URL=postgresql://postgres:12345@db:5432/prisma?schema=public
      - NODE_PORT=3000
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
      - NODE_ENV=dev
    command: npx nodemon src/server.ts
    volumes:
      - ./nest:/nest
    working_dir: /nest
    depends_on:
      db:
        condition: service_healthy
      
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 12345
    volumes:
      - /portainer/postgres/games-dev:/var/lib/postgresql/data
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120