name: games-test
services:
  app:
    build:
      context: ./app
    image: ghcr.io/jcubby86/games-app:test
    ports:
      - 3021:80
    environment:
      - NGINX_BACKEND_ADDRESS=http://backend:3000
    depends_on: 
      - backend

  backend:
    build:
      context: ./nest
    image: ghcr.io/jcubby86/games-backend:test
    ports :
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
      - NODE_ENV=production
      - JWT_SECRET=123123
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:17.2
    restart: unless-stopped
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
