name: games-test
services:
  app:
    build:
      context: ./app
    image: ghcr.io/jcubby86/games-app:test
    ports:
      - 3021:80
    environment:
      - NGINX_BACKEND_ADDRESS=http://backend:3000
    restart: unless-stopped
    depends_on: 
      - backend

  backend:
    build:
      context: ./nest
    image: ghcr.io/jcubby86/games-backend:test
    ports :
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/postgres
      - NODE_ENV=development
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql
    healthcheck:
      test: /usr/bin/pg_isready

volumes:
  db-data:
