name: games
services:
  app:
    image: ghcr.io/jcubby86/games-app:latest
    ports:
      - 3020:80
    environment:
      - NGINX_BACKEND_ADDRESS=http://backend:3000
    restart: unless-stopped
    depends_on: 
      - backend

  backend:
    image: ghcr.io/jcubby86/games-backend:latest
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/postgres
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: /usr/bin/pg_isready

volumes:
  db-data:
